### ISSUE TITLE
Fix flask security alert 

### ISSUE THREAD

**Issue by ramdootp** [CiscoAI/KFLab#116]
https://github.com/CiscoAI/KFLab/network/alert/tf-mnist/webapp/requirements.txt/flask/open
@prem0912

**Comment by ramdootp** [comment]
@kraghupathi

**Comment by kraghupathi** [comment]
@ramdootp :   

Upgraded Flask version to 0.12.3 and created PR

**Comment by ramdootp** [comment]
Resolved
