### ISSUE TITLE
change name of repo

### ISSUE THREAD

**Issue by ddutta** [CiscoAI/KFLab#57]
Right now this does more than workflows

**Comment by amsaha** [comment]
Candidates?

**Comment by amsaha** [comment]
As of now candidates are:

- [ ] KFLab
- [ ] ML-Lab

@ddutta @xyhuang @swiftdiaries any other suggestions?

**Comment by amsaha** [comment]
We will go with KFLab

**Comment by amsaha** [comment]
Pending https://github.com/CiscoAI/ai-test-infra/issues/3.

**Comment by ramdootp** [comment]
Changes merged

**Comment by amsaha** [comment]
Closed via https://github.com/CiscoAI/KFLab/pull/70
